package zwz.greendao.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import zwz.greendao.bean.User;
import zwz.greendao.bean.Animal;

import zwz.greendao.greendao.UserDao;
import zwz.greendao.greendao.AnimalDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig animalDaoConfig;

    private final UserDao userDao;
    private final AnimalDao animalDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        animalDaoConfig = daoConfigMap.get(AnimalDao.class).clone();
        animalDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        animalDao = new AnimalDao(animalDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Animal.class, animalDao);
    }
    
    public void clear() {
        userDaoConfig.clearIdentityScope();
        animalDaoConfig.clearIdentityScope();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public AnimalDao getAnimalDao() {
        return animalDao;
    }

}
