package zwz.greendao.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import zwz.greendao.bean.User;
import zwz.greendao.bean.Animal;
import zwz.greendao.bean.Test;
import zwz.greendao.bean.Test2;

import zwz.greendao.greendao.UserDao;
import zwz.greendao.greendao.AnimalDao;
import zwz.greendao.greendao.TestDao;
import zwz.greendao.greendao.Test2Dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig animalDaoConfig;
    private final DaoConfig testDaoConfig;
    private final DaoConfig test2DaoConfig;

    private final UserDao userDao;
    private final AnimalDao animalDao;
    private final TestDao testDao;
    private final Test2Dao test2Dao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        animalDaoConfig = daoConfigMap.get(AnimalDao.class).clone();
        animalDaoConfig.initIdentityScope(type);

        testDaoConfig = daoConfigMap.get(TestDao.class).clone();
        testDaoConfig.initIdentityScope(type);

        test2DaoConfig = daoConfigMap.get(Test2Dao.class).clone();
        test2DaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        animalDao = new AnimalDao(animalDaoConfig, this);
        testDao = new TestDao(testDaoConfig, this);
        test2Dao = new Test2Dao(test2DaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Animal.class, animalDao);
        registerDao(Test.class, testDao);
        registerDao(Test2.class, test2Dao);
    }
    
    public void clear() {
        userDaoConfig.clearIdentityScope();
        animalDaoConfig.clearIdentityScope();
        testDaoConfig.clearIdentityScope();
        test2DaoConfig.clearIdentityScope();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public AnimalDao getAnimalDao() {
        return animalDao;
    }

    public TestDao getTestDao() {
        return testDao;
    }

    public Test2Dao getTest2Dao() {
        return test2Dao;
    }

}
